services:
  - type: web
    name: bpms-v13-beta-user-v4
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4.1-nano
      - key: OPENAI_TRANSCRIBE_MODEL
        value: gpt-4o-mini-transcribe
